/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as InspectionsIndexRouteImport } from './routes/inspections.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as InspectionsCalendarRouteImport } from './routes/inspections.calendar'
import { Route as InspectionsIdIndexRouteImport } from './routes/inspections.$id.index'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsIndexRoute = InspectionsIndexRouteImport.update({
  id: '/inspections/',
  path: '/inspections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsCalendarRoute = InspectionsCalendarRouteImport.update({
  id: '/inspections/calendar',
  path: '/inspections/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsIdIndexRoute = InspectionsIdIndexRouteImport.update({
  id: '/inspections/$id/',
  path: '/inspections/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/inspections/calendar': typeof InspectionsCalendarRoute
  '/products/$id': typeof ProductsIdRoute
  '/inspections/': typeof InspectionsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/inspections/$id/': typeof InspectionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/inspections/calendar': typeof InspectionsCalendarRoute
  '/products/$id': typeof ProductsIdRoute
  '/inspections': typeof InspectionsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/inspections/$id': typeof InspectionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/inspections/calendar': typeof InspectionsCalendarRoute
  '/products/$id': typeof ProductsIdRoute
  '/inspections/': typeof InspectionsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/inspections/$id/': typeof InspectionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/inspections/calendar'
    | '/products/$id'
    | '/inspections/'
    | '/products/'
    | '/inspections/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/inspections/calendar'
    | '/products/$id'
    | '/inspections'
    | '/products'
    | '/inspections/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/inspections/calendar'
    | '/products/$id'
    | '/inspections/'
    | '/products/'
    | '/inspections/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  InspectionsCalendarRoute: typeof InspectionsCalendarRoute
  ProductsIdRoute: typeof ProductsIdRoute
  InspectionsIndexRoute: typeof InspectionsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  InspectionsIdIndexRoute: typeof InspectionsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections/': {
      id: '/inspections/'
      path: '/inspections'
      fullPath: '/inspections/'
      preLoaderRoute: typeof InspectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections/calendar': {
      id: '/inspections/calendar'
      path: '/inspections/calendar'
      fullPath: '/inspections/calendar'
      preLoaderRoute: typeof InspectionsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections/$id/': {
      id: '/inspections/$id/'
      path: '/inspections/$id'
      fullPath: '/inspections/$id/'
      preLoaderRoute: typeof InspectionsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  InspectionsCalendarRoute: InspectionsCalendarRoute,
  ProductsIdRoute: ProductsIdRoute,
  InspectionsIndexRoute: InspectionsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  InspectionsIdIndexRoute: InspectionsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
