/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpcRouteImport } from './routes/spc'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkOrdersIndexRouteImport } from './routes/work-orders.index'
import { Route as StationsIndexRouteImport } from './routes/stations.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as NonConformancesIndexRouteImport } from './routes/non-conformances.index'
import { Route as LinesIndexRouteImport } from './routes/lines.index'
import { Route as InspectionsIndexRouteImport } from './routes/inspections.index'
import { Route as InspectionPlansIndexRouteImport } from './routes/inspection-plans.index'
import { Route as HoldsIndexRouteImport } from './routes/holds.index'
import { Route as CorrectiveActionsIndexRouteImport } from './routes/corrective-actions.index'
import { Route as CalibrationIndexRouteImport } from './routes/calibration.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as NonConformancesListRouteImport } from './routes/non-conformances.list'
import { Route as NonConformancesIdRouteImport } from './routes/non-conformances.$id'
import { Route as InspectionsCalendarRouteImport } from './routes/inspections.calendar'
import { Route as CorrectiveActionsIdRouteImport } from './routes/corrective-actions.$id'
import { Route as InspectionsIdIndexRouteImport } from './routes/inspections.$id.index'
import { Route as InspectionsIdExecuteRouteImport } from './routes/inspections.$id.execute'

const SpcRoute = SpcRouteImport.update({
  id: '/spc',
  path: '/spc',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersIndexRoute = WorkOrdersIndexRouteImport.update({
  id: '/work-orders/',
  path: '/work-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsIndexRoute = StationsIndexRouteImport.update({
  id: '/stations/',
  path: '/stations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const NonConformancesIndexRoute = NonConformancesIndexRouteImport.update({
  id: '/non-conformances/',
  path: '/non-conformances/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinesIndexRoute = LinesIndexRouteImport.update({
  id: '/lines/',
  path: '/lines/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsIndexRoute = InspectionsIndexRouteImport.update({
  id: '/inspections/',
  path: '/inspections/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionPlansIndexRoute = InspectionPlansIndexRouteImport.update({
  id: '/inspection-plans/',
  path: '/inspection-plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldsIndexRoute = HoldsIndexRouteImport.update({
  id: '/holds/',
  path: '/holds/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectiveActionsIndexRoute = CorrectiveActionsIndexRouteImport.update({
  id: '/corrective-actions/',
  path: '/corrective-actions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrationIndexRoute = CalibrationIndexRouteImport.update({
  id: '/calibration/',
  path: '/calibration/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NonConformancesListRoute = NonConformancesListRouteImport.update({
  id: '/non-conformances/list',
  path: '/non-conformances/list',
  getParentRoute: () => rootRouteImport,
} as any)
const NonConformancesIdRoute = NonConformancesIdRouteImport.update({
  id: '/non-conformances/$id',
  path: '/non-conformances/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsCalendarRoute = InspectionsCalendarRouteImport.update({
  id: '/inspections/calendar',
  path: '/inspections/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectiveActionsIdRoute = CorrectiveActionsIdRouteImport.update({
  id: '/corrective-actions/$id',
  path: '/corrective-actions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsIdIndexRoute = InspectionsIdIndexRouteImport.update({
  id: '/inspections/$id/',
  path: '/inspections/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsIdExecuteRoute = InspectionsIdExecuteRouteImport.update({
  id: '/inspections/$id/execute',
  path: '/inspections/$id/execute',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/spc': typeof SpcRoute
  '/corrective-actions/$id': typeof CorrectiveActionsIdRoute
  '/inspections/calendar': typeof InspectionsCalendarRoute
  '/non-conformances/$id': typeof NonConformancesIdRoute
  '/non-conformances/list': typeof NonConformancesListRoute
  '/products/$id': typeof ProductsIdRoute
  '/calibration/': typeof CalibrationIndexRoute
  '/corrective-actions/': typeof CorrectiveActionsIndexRoute
  '/holds/': typeof HoldsIndexRoute
  '/inspection-plans/': typeof InspectionPlansIndexRoute
  '/inspections/': typeof InspectionsIndexRoute
  '/lines/': typeof LinesIndexRoute
  '/non-conformances/': typeof NonConformancesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/stations/': typeof StationsIndexRoute
  '/work-orders/': typeof WorkOrdersIndexRoute
  '/inspections/$id/execute': typeof InspectionsIdExecuteRoute
  '/inspections/$id/': typeof InspectionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/spc': typeof SpcRoute
  '/corrective-actions/$id': typeof CorrectiveActionsIdRoute
  '/inspections/calendar': typeof InspectionsCalendarRoute
  '/non-conformances/$id': typeof NonConformancesIdRoute
  '/non-conformances/list': typeof NonConformancesListRoute
  '/products/$id': typeof ProductsIdRoute
  '/calibration': typeof CalibrationIndexRoute
  '/corrective-actions': typeof CorrectiveActionsIndexRoute
  '/holds': typeof HoldsIndexRoute
  '/inspection-plans': typeof InspectionPlansIndexRoute
  '/inspections': typeof InspectionsIndexRoute
  '/lines': typeof LinesIndexRoute
  '/non-conformances': typeof NonConformancesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/stations': typeof StationsIndexRoute
  '/work-orders': typeof WorkOrdersIndexRoute
  '/inspections/$id/execute': typeof InspectionsIdExecuteRoute
  '/inspections/$id': typeof InspectionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/spc': typeof SpcRoute
  '/corrective-actions/$id': typeof CorrectiveActionsIdRoute
  '/inspections/calendar': typeof InspectionsCalendarRoute
  '/non-conformances/$id': typeof NonConformancesIdRoute
  '/non-conformances/list': typeof NonConformancesListRoute
  '/products/$id': typeof ProductsIdRoute
  '/calibration/': typeof CalibrationIndexRoute
  '/corrective-actions/': typeof CorrectiveActionsIndexRoute
  '/holds/': typeof HoldsIndexRoute
  '/inspection-plans/': typeof InspectionPlansIndexRoute
  '/inspections/': typeof InspectionsIndexRoute
  '/lines/': typeof LinesIndexRoute
  '/non-conformances/': typeof NonConformancesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/stations/': typeof StationsIndexRoute
  '/work-orders/': typeof WorkOrdersIndexRoute
  '/inspections/$id/execute': typeof InspectionsIdExecuteRoute
  '/inspections/$id/': typeof InspectionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/live'
    | '/login'
    | '/profile'
    | '/reports'
    | '/spc'
    | '/corrective-actions/$id'
    | '/inspections/calendar'
    | '/non-conformances/$id'
    | '/non-conformances/list'
    | '/products/$id'
    | '/calibration/'
    | '/corrective-actions/'
    | '/holds/'
    | '/inspection-plans/'
    | '/inspections/'
    | '/lines/'
    | '/non-conformances/'
    | '/products/'
    | '/stations/'
    | '/work-orders/'
    | '/inspections/$id/execute'
    | '/inspections/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/live'
    | '/login'
    | '/profile'
    | '/reports'
    | '/spc'
    | '/corrective-actions/$id'
    | '/inspections/calendar'
    | '/non-conformances/$id'
    | '/non-conformances/list'
    | '/products/$id'
    | '/calibration'
    | '/corrective-actions'
    | '/holds'
    | '/inspection-plans'
    | '/inspections'
    | '/lines'
    | '/non-conformances'
    | '/products'
    | '/stations'
    | '/work-orders'
    | '/inspections/$id/execute'
    | '/inspections/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/live'
    | '/login'
    | '/profile'
    | '/reports'
    | '/spc'
    | '/corrective-actions/$id'
    | '/inspections/calendar'
    | '/non-conformances/$id'
    | '/non-conformances/list'
    | '/products/$id'
    | '/calibration/'
    | '/corrective-actions/'
    | '/holds/'
    | '/inspection-plans/'
    | '/inspections/'
    | '/lines/'
    | '/non-conformances/'
    | '/products/'
    | '/stations/'
    | '/work-orders/'
    | '/inspections/$id/execute'
    | '/inspections/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SpcRoute: typeof SpcRoute
  CorrectiveActionsIdRoute: typeof CorrectiveActionsIdRoute
  InspectionsCalendarRoute: typeof InspectionsCalendarRoute
  NonConformancesIdRoute: typeof NonConformancesIdRoute
  NonConformancesListRoute: typeof NonConformancesListRoute
  ProductsIdRoute: typeof ProductsIdRoute
  CalibrationIndexRoute: typeof CalibrationIndexRoute
  CorrectiveActionsIndexRoute: typeof CorrectiveActionsIndexRoute
  HoldsIndexRoute: typeof HoldsIndexRoute
  InspectionPlansIndexRoute: typeof InspectionPlansIndexRoute
  InspectionsIndexRoute: typeof InspectionsIndexRoute
  LinesIndexRoute: typeof LinesIndexRoute
  NonConformancesIndexRoute: typeof NonConformancesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  StationsIndexRoute: typeof StationsIndexRoute
  WorkOrdersIndexRoute: typeof WorkOrdersIndexRoute
  InspectionsIdExecuteRoute: typeof InspectionsIdExecuteRoute
  InspectionsIdIndexRoute: typeof InspectionsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spc': {
      id: '/spc'
      path: '/spc'
      fullPath: '/spc'
      preLoaderRoute: typeof SpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders/': {
      id: '/work-orders/'
      path: '/work-orders'
      fullPath: '/work-orders/'
      preLoaderRoute: typeof WorkOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/': {
      id: '/stations/'
      path: '/stations'
      fullPath: '/stations/'
      preLoaderRoute: typeof StationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/non-conformances/': {
      id: '/non-conformances/'
      path: '/non-conformances'
      fullPath: '/non-conformances/'
      preLoaderRoute: typeof NonConformancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lines/': {
      id: '/lines/'
      path: '/lines'
      fullPath: '/lines/'
      preLoaderRoute: typeof LinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections/': {
      id: '/inspections/'
      path: '/inspections'
      fullPath: '/inspections/'
      preLoaderRoute: typeof InspectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection-plans/': {
      id: '/inspection-plans/'
      path: '/inspection-plans'
      fullPath: '/inspection-plans/'
      preLoaderRoute: typeof InspectionPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holds/': {
      id: '/holds/'
      path: '/holds'
      fullPath: '/holds/'
      preLoaderRoute: typeof HoldsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrective-actions/': {
      id: '/corrective-actions/'
      path: '/corrective-actions'
      fullPath: '/corrective-actions/'
      preLoaderRoute: typeof CorrectiveActionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibration/': {
      id: '/calibration/'
      path: '/calibration'
      fullPath: '/calibration/'
      preLoaderRoute: typeof CalibrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/non-conformances/list': {
      id: '/non-conformances/list'
      path: '/non-conformances/list'
      fullPath: '/non-conformances/list'
      preLoaderRoute: typeof NonConformancesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/non-conformances/$id': {
      id: '/non-conformances/$id'
      path: '/non-conformances/$id'
      fullPath: '/non-conformances/$id'
      preLoaderRoute: typeof NonConformancesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections/calendar': {
      id: '/inspections/calendar'
      path: '/inspections/calendar'
      fullPath: '/inspections/calendar'
      preLoaderRoute: typeof InspectionsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrective-actions/$id': {
      id: '/corrective-actions/$id'
      path: '/corrective-actions/$id'
      fullPath: '/corrective-actions/$id'
      preLoaderRoute: typeof CorrectiveActionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections/$id/': {
      id: '/inspections/$id/'
      path: '/inspections/$id'
      fullPath: '/inspections/$id/'
      preLoaderRoute: typeof InspectionsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections/$id/execute': {
      id: '/inspections/$id/execute'
      path: '/inspections/$id/execute'
      fullPath: '/inspections/$id/execute'
      preLoaderRoute: typeof InspectionsIdExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SpcRoute: SpcRoute,
  CorrectiveActionsIdRoute: CorrectiveActionsIdRoute,
  InspectionsCalendarRoute: InspectionsCalendarRoute,
  NonConformancesIdRoute: NonConformancesIdRoute,
  NonConformancesListRoute: NonConformancesListRoute,
  ProductsIdRoute: ProductsIdRoute,
  CalibrationIndexRoute: CalibrationIndexRoute,
  CorrectiveActionsIndexRoute: CorrectiveActionsIndexRoute,
  HoldsIndexRoute: HoldsIndexRoute,
  InspectionPlansIndexRoute: InspectionPlansIndexRoute,
  InspectionsIndexRoute: InspectionsIndexRoute,
  LinesIndexRoute: LinesIndexRoute,
  NonConformancesIndexRoute: NonConformancesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  StationsIndexRoute: StationsIndexRoute,
  WorkOrdersIndexRoute: WorkOrdersIndexRoute,
  InspectionsIdExecuteRoute: InspectionsIdExecuteRoute,
  InspectionsIdIndexRoute: InspectionsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
